const businessTypes=[
  {id:"trade",icon:"trade",name:"Trading",note:"Import & export"},{id:"digital",icon:"digital",name:"Digital commerce",note:"Online sales"},{id:"food",icon:"food",name:"Food & beverage",note:"Restaurants & retail"},{id:"services",icon:"services",name:"Professional services",note:"Client-led work"},
  {id:"tech",icon:"tech",name:"Technology",note:"Software & platforms"},{id:"manufacturing",icon:"manufacturing",name:"Manufacturing",note:"Production & supply"},{id:"health",icon:"health",name:"Healthcare",note:"Health & wellness"},{id:"property",icon:"property",name:"Property",note:"Real estate services"}
];
const solutions=[
  ["Business Internet Banking","Always connected","banking"],["Payments and Liquidity","Recommended","payments"],["Commercial Wealth","Build resilience","wealth"],["Financing & Credit Cards","Fuel the next move","finance"],["Global Trade Solutions","Grow across borders","global"]
];
const journey=["Business","Permission","Readiness","Account","Grow"];
let step=0,business="digital",consent=false,unlocked=["Business Internet Banking"];
const panel=document.getElementById("demoPanel"),rail=document.getElementById("journeyRail"),count=document.getElementById("stepCount");
const svg=name=>window.NextGem.icon(name);

function renderRail(){rail.innerHTML=journey.map((label,index)=>`<li class="${index===step?"current":index<step?"complete":""}"><i>${index<step?"✓":index+1}</i><span>${label}</span></li>`).join("");count.textContent=`Step ${step+1} of ${journey.length}`;}
function actions(back=true,nextLabel="Continue",disabled=false,nextId="next"){return `<div class="demoActions">${back?'<button class="demoBack" id="back">← Back</button>':"<span></span>"}<button class="demoPrimary" id="${nextId}" ${disabled?"disabled":""}>${nextLabel} <b>→</b></button></div>`;}
function selected(){return businessTypes.find(item=>item.id===business)||businessTypes[1];}

function render(){
  renderRail();
  if(step===0){panel.innerHTML=`<p class="demoEyebrow">LET'S BEGIN</p><h2>What kind of business<br>are you building?</h2><p class="demoIntro">We use this to personalise the journey and show only the actions that matter.</p><div class="businessGrid">${businessTypes.map(item=>`<button class="${item.id===business?"selected":""}" data-business="${item.id}" aria-pressed="${item.id===business}"><span>${svg(item.icon)}</span><b>${item.name}</b><small>${item.note}</small><i>✓</i></button>`).join("")}</div>${actions(false)}`;}
  if(step===1){const item=selected();panel.innerHTML=`<p class="demoEyebrow">USE WHAT IS ALREADY TRUSTED</p><h2>Less to type.<br>More time to build.</h2><p class="demoIntro">With your permission, verified information can be retrieved without asking for it again.</p><div class="consentCard"><div class="consentIcon">${svg("permission")}</div><div><h3>Retrieve my verified business profile</h3><p>Demo sources: digital identity, business registry and existing verified records.</p><button class="consentToggle ${consent?"on":""}" id="consent" role="switch" aria-checked="${consent}"><i></i><span>${consent?"Permission given":"Give permission"}</span></button></div></div><div class="dataPreview"><span>PREPARED FOR YOU</span><div><p>Business type<b>${item.name}</b></p><p>Company name<b>Next GEM Company Limited</b></p><p>Ownership<b>Single director</b></p></div><small>Fictional information for demonstration only</small></div>${actions(true,"Use verified profile",!consent)}`;}
  if(step===2){panel.innerHTML=`<p class="demoEyebrow">ESSENTIAL CHECKS ONLY</p><h2>Ready for your<br>first milestone.</h2><p class="demoIntro">We have enough trusted information to assess an initial account for this fictional eligible business.</p><div class="checkList"><div><i>${svg("identity")}</i><span><b>Identity recognised</b><small>Secure digital identity</small></span><em>Ready</em></div><div><i>${svg("profile")}</i><span><b>Business profile matched</b><small>Trusted registry information</small></span><em>Ready</em></div><div><i>${svg("insight")}</i><span><b>Initial risk indicators</b><small>Essential information reviewed</small></span><em>Ready</em></div></div><div class="plainPromise"><span>WHY ONLY THESE CHECKS?</span><p>They are the minimum needed for this first safe milestone. Every future request will explain what it unlocks.</p></div>${actions(true,"Create demo account",false,"create")}`;}
  if(step===3){panel.innerHTML=`<div class="successPulse">✓</div><p class="demoEyebrow">FIRST MILESTONE COMPLETE</p><h2>Your business can<br><em>start moving.</em></h2><p class="demoIntro">A masked demo account is ready. Your next steps are visible, and more services can unlock as your needs grow.</p><div class="accountCard"><div><span>NEXT GEM · DEMO</span><b>Next GEM Company Limited</b></div><p>MASKED DEMO ACCOUNT</p><strong>***-******-838</strong><small>Secured display · Fictional demonstration only</small></div><div class="timeSaved"><strong>02:41</strong><span><b>Journey time</b>Under the 3-minute ambition</span><i>Milestone 1 of 4</i></div>${actions(true,"Enter my account")}`;}
  if(step===4){panel.innerHTML=`<div class="dashboardHello"><div><p class="demoEyebrow">GOOD MORNING, ALEX</p><h2>Your business,<br><em>ready to grow.</em></h2></div><button id="restart">Restart demo ↻</button></div><div class="accountStatus"><div><span>ACCOUNT STATUS</span><b><i></i> Active · Essentials ready</b></div><p>Next GEM Company Limited<small>***-******-838 · Secured display</small></p></div><div class="nextAction"><span>YOUR NEXT BEST STEP</span><div><i>${svg("payments")}</i><p><b>Move money with confidence</b>Payments and liquidity tools are ready to support everyday cash flow.</p><button data-unlock="Payments and Liquidity">${unlocked.includes("Payments and Liquidity")?"Added ✓":"Explore →"}</button></div></div><p class="serviceTitle">PRODUCTS AND SOLUTIONS THAT GROW WITH YOU</p><div class="serviceGrid">${solutions.map(([name,status,icon])=>{const active=unlocked.includes(name);return `<button class="service ${active?"active":""}" data-unlock="${name}"><i>${active?"✓":svg(icon)}</i><b>${name}</b><span>${active?"Unlocked":status}</span></button>`;}).join("")}</div><div class="demoFinish"><span>♡</span><p><b>One relationship. No restart.</b>Your profile, progress and permissions move with you.</p><a href="index.html">Return to pitch →</a></div>`;}
  bind();
}

function bind(){
  document.querySelectorAll("[data-business]").forEach(button=>button.addEventListener("click",()=>{business=button.dataset.business;render();}));
  const consentButton=document.getElementById("consent");if(consentButton)consentButton.addEventListener("click",()=>{consent=!consent;render();});
  const back=document.getElementById("back");if(back)back.addEventListener("click",()=>{step=Math.max(0,step-1);render();window.scrollTo({top:0,behavior:"smooth"});});
  const next=document.getElementById("next");if(next)next.addEventListener("click",()=>{step=Math.min(4,step+1);render();window.scrollTo({top:0,behavior:"smooth"});});
  const create=document.getElementById("create");if(create)create.addEventListener("click",()=>{create.disabled=true;create.textContent="Running secure checks…";setTimeout(()=>{step=3;render();window.scrollTo({top:0,behavior:"smooth"});},900);});
  const restart=document.getElementById("restart");if(restart)restart.addEventListener("click",()=>{step=0;business="digital";consent=false;unlocked=["Business Internet Banking"];render();});
  document.querySelectorAll("[data-unlock]").forEach(button=>button.addEventListener("click",()=>{const name=button.dataset.unlock;if(!unlocked.includes(name))unlocked.push(name);render();}));
}
render();
